index:
    path: /
    controller: App\Controller\ArticleController::homepage
new:
    path: /news/{notice}
    controller: App\Controller\ArticleController::show
article_toggle_heart:
    path: /news/{notice}/heart
    controller: App\Controller\ArticleController::toggleArticleHeart
    methods: POST
article_new:
    path: /admin/article/new
    controller: App\Controller\ArticleAdminController::new
get_post:
    path: /admin/article/get
    controller: App\Controller\ArticleAdminController::getArticles
